import type {SystemId} from '@/atlas/anatomy';

/**
 * The only structures the planner is allowed to reference. Each entry maps a friendly,
 * bilingual key onto one or more named concepts in the BodyParts3D catalogue.
 */
export interface RegistryEntry {
  key: string;
  name: string;
  system: SystemId;
  concepts: string[];
  aliases: string[];
}

export const REGISTRY: RegistryEntry[] = [
  {key: 'heart', name: 'Heart', system: 'cardiac', concepts: ['heart'],
    aliases: ['jantung', 'cardiac muscle', 'myocardium']},
  {key: 'lungs', name: 'Lungs', system: 'respiratory', concepts: ['right lung', 'left lung'],
    aliases: ['lung', 'paru paru', 'paru', 'pulmonary']},
  {key: 'trachea', name: 'Trachea', system: 'respiratory', concepts: ['trachea'],
    aliases: ['windpipe', 'tenggorokan', 'trakea', 'airway']},
  {key: 'bronchus', name: 'Bronchus', system: 'respiratory', concepts: ['bronchus'],
    aliases: ['bronchi', 'bronkus', 'bronchial']},
  {key: 'larynx', name: 'Larynx', system: 'respiratory', concepts: ['muscle of larynx', 'intrinsic ligament of larynx'],
    aliases: ['voice box', 'laring', 'pita suara', 'vocal cords']},
  {key: 'nose', name: 'Nose', system: 'respiratory', concepts: ['nose', 'internal nose'],
    aliases: ['nasal', 'hidung', 'nostril']},
  {key: 'diaphragm', name: 'Diaphragm', system: 'muscular', concepts: ['diaphragm'],
    aliases: ['diafragma', 'breathing muscle']},
  {key: 'mouth', name: 'Mouth', system: 'digestive', concepts: ['mouth'],
    aliases: ['oral cavity', 'mulut', 'rongga mulut']},
  {key: 'tongue', name: 'Tongue', system: 'digestive', concepts: ['tongue'],
    aliases: ['lidah']},
  {key: 'esophagus', name: 'Esophagus', system: 'digestive', concepts: ['esophagus'],
    aliases: ['food pipe', 'kerongkongan', 'esofagus']},
  {key: 'stomach', name: 'Stomach', system: 'digestive', concepts: ['stomach'],
    aliases: ['lambung', 'maag', 'perut', 'gastric']},
  {key: 'small_intestine', name: 'Small intestine', system: 'digestive', concepts: ['small intestine'],
    aliases: ['usus halus', 'intestine', 'duodenum']},
  {key: 'large_intestine', name: 'Large intestine', system: 'digestive', concepts: ['large intestine'],
    aliases: ['colon', 'usus besar', 'bowel']},
  {key: 'liver', name: 'Liver', system: 'digestive', concepts: ['liver'],
    aliases: ['hati', 'hepatic']},
  {key: 'pancreas', name: 'Pancreas', system: 'digestive', concepts: ['pancreas'],
    aliases: ['pankreas', 'insulin']},
  {key: 'spleen', name: 'Spleen', system: 'lymphatic', concepts: ['spleen'],
    aliases: ['limpa']},
  {key: 'kidneys', name: 'Kidneys', system: 'urinary', concepts: ['kidney', 'right kidney', 'left kidney'],
    aliases: ['ginjal', 'renal', 'kidney']},
  {key: 'bladder', name: 'Urinary bladder', system: 'urinary', concepts: ['urinary bladder'],
    aliases: ['bladder', 'kandung kemih', 'kantung kemih']},
  {key: 'brain', name: 'Brain', system: 'nervous', concepts: ['brain'],
    aliases: ['otak', 'cerebrum', 'cortex']},
  {key: 'hypothalamus', name: 'Hypothalamus', system: 'nervous', concepts: ['hypothalamus'],
    aliases: ['hipotalamus']},
  {key: 'brainstem', name: 'Brainstem', system: 'nervous', concepts: ['medulla oblongata'],
    aliases: ['brain stem', 'batang otak', 'medulla']},
  {key: 'spinal_cord', name: 'Spinal cord', system: 'nervous', concepts: ['spinal cord'],
    aliases: ['sumsum tulang belakang', 'spine cord']},
  {key: 'nerves', name: 'Nerves', system: 'nervous', concepts: ['nerve trunk'],
    aliases: ['nerve', 'saraf', 'peripheral nerves']},
  {key: 'pituitary', name: 'Pituitary gland', system: 'endocrine', concepts: ['pituitary gland'],
    aliases: ['hipofisis', 'master gland']},
  {key: 'pineal', name: 'Pineal body', system: 'endocrine', concepts: ['pineal body'],
    aliases: ['pineal gland', 'kelenjar pineal', 'melatonin']},
  {key: 'adrenal', name: 'Adrenal gland', system: 'endocrine', concepts: ['adrenal gland'],
    aliases: ['anak ginjal', 'adrenaline', 'kelenjar adrenal']},
  {key: 'thymus', name: 'Thymus', system: 'lymphatic', concepts: ['thymus'],
    aliases: ['timus']},
  {key: 'skull', name: 'Skull', system: 'skeletal', concepts: ['skull'],
    aliases: ['cranium', 'tengkorak', 'kepala']},
  {key: 'ribs', name: 'Ribs', system: 'skeletal', concepts: ['rib'],
    aliases: ['rib', 'rusuk', 'tulang rusuk', 'rib cage']},
  {key: 'spine', name: 'Spine', system: 'skeletal', concepts: ['vertebra'],
    aliases: ['vertebrae', 'tulang belakang', 'backbone', 'vertebral column']},
  {key: 'pelvis', name: 'Pelvis', system: 'skeletal', concepts: ['pelvis'],
    aliases: ['panggul', 'tulang panggul', 'hip bone']},
  {key: 'femur', name: 'Femur', system: 'skeletal', concepts: ['femur'],
    aliases: ['thigh bone', 'tulang paha']},
  {key: 'tibia', name: 'Tibia', system: 'skeletal', concepts: ['tibia'],
    aliases: ['shin bone', 'tulang kering']},
  {key: 'humerus', name: 'Humerus', system: 'skeletal', concepts: ['humerus'],
    aliases: ['upper arm bone', 'tulang lengan atas']},
  {key: 'scapula', name: 'Scapula', system: 'skeletal', concepts: ['scapula'],
    aliases: ['shoulder blade', 'tulang belikat']},
  {key: 'skeleton', name: 'Skeleton', system: 'skeletal',
    concepts: ['skull', 'rib', 'vertebra', 'pelvis', 'femur', 'tibia', 'humerus', 'scapula'],
    aliases: ['bones', 'tulang', 'kerangka', 'skeletal system']},
  {key: 'muscles', name: 'Muscles', system: 'muscular', concepts: ['muscle organ'],
    aliases: ['muscle', 'otot', 'muscular system']},
  {key: 'quadriceps', name: 'Quadriceps', system: 'muscular', concepts: ['zone of quadriceps femoris'],
    aliases: ['quad', 'otot paha depan', 'thigh muscles', 'otot paha']},
  {key: 'thigh', name: 'Thigh muscles', system: 'muscular', concepts: ['muscle of thigh'],
    aliases: ['paha', 'hamstring', 'otot paha belakang']},
  {key: 'calf', name: 'Calf muscles', system: 'muscular',
    concepts: ['medial head of gastrocnemius', 'lateral head of gastrocnemius'],
    aliases: ['betis', 'otot betis', 'gastrocnemius']},
  {key: 'biceps', name: 'Biceps', system: 'muscular',
    concepts: ['short head of biceps brachii', 'long head of biceps brachii'],
    aliases: ['bisep', 'biceps brachii']},
  {key: 'triceps', name: 'Triceps', system: 'muscular',
    concepts: ['long head of triceps brachii', 'medial head of triceps brachii', 'lateral head of triceps brachii'],
    aliases: ['trisep', 'triceps brachii']},
  {key: 'deltoid', name: 'Deltoid', system: 'muscular', concepts: ['zone of deltoid'],
    aliases: ['shoulder muscle', 'otot bahu', 'bahu']},
  {key: 'aorta', name: 'Aorta', system: 'arterial', concepts: ['aorta'],
    aliases: ['pembuluh besar', 'main artery']},
  {key: 'arteries', name: 'Arteries', system: 'arterial', concepts: ['segment of artery', 'aorta'],
    aliases: ['artery', 'arteri', 'pembuluh nadi', 'nadi']},
  {key: 'veins', name: 'Veins', system: 'venous', concepts: ['venous tree organ'],
    aliases: ['vein', 'vena', 'pembuluh balik', 'pembuluh vena']},
  {key: 'blood_vessels', name: 'Blood vessels', system: 'arterial',
    concepts: ['region of vascular tree organ', 'aorta'],
    aliases: ['circulatory system', 'blood', 'pembuluh darah', 'darah', 'circulation', 'vascular', 'blood vessel']},
  {key: 'skin', name: 'Skin', system: 'integumentary', concepts: ['skin'],
    aliases: ['kulit', 'body surface']},
  {key: 'eye', name: 'Eye', system: 'sensory', concepts: ['layer of wall of eyeball', 'chamber of eyeball'],
    aliases: ['eyeball', 'mata', 'retina']},
  {key: 'prostate', name: 'Prostate', system: 'reproductive', concepts: ['prostate'],
    aliases: ['prostat']},
  {key: 'testis', name: 'Testis', system: 'reproductive', concepts: ['testis'],
    aliases: ['testicle', 'testes']},
];
